/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kuesionerfix.components;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import kuesionerfix.DBConnection;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asus
 */
public class table2 extends javax.swing.JPanel {

    private int idSelectedPerusahaan;
    private int idRegistrasi;

    /**
     * Creates new form table3
     */
    public table2() {
        initComponents();
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(32, 136, 203));
        jTable1.getTableHeader().setForeground(new Color(255, 255, 255));
        jTable1.setRowHeight(25);

    }

    public void loadTablePerusahaan() {
        String sql = "SELECT * FROM perusahaan WHERE id_registrasi = '" + idRegistrasi + "'";
        try {
            Connection connection = DBConnection.getConnection();
            Statement stmt = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    public void searchByKecamatan(String kodeKecamatan) {
        if (kodeKecamatan.contains("--")) {
            loadTablePerusahaan();
            return;
        }
        String sql = "SELECT * FROM perusahaan WHERE kode_kec = '" + kodeKecamatan + "'";
        try {
            Connection connection = DBConnection.getConnection();
            Statement stmt = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                                null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                                null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                                null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                                null, null, null, null, null, null }
                },
                new String[] {
                        "Action", "No", "Kode Prov", "Kode Kab", "Kode Kec", "Kode KJU", "No. Urut dalam Satu Kab/Kota",
                        "Nama Perusahaan", "Alamat Perusahaan", "No. Telp", "No. Faksimili", "Bentuk Badan Hukum",
                        "Ket. Kunjungan", "Status", "Tanaman Pangan", "Hortikultura", "Perkebunan", "Peternakan",
                        "Kehutanan", "Perikanan", "Jenis Usaha Utama"
                }) {
            Class[] types = new Class[] {
                    java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class,
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
                    java.lang.Boolean.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class,
                    java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class,
                    java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(30);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(6).setMinWidth(150);
            jTable1.getColumnModel().getColumn(7).setMinWidth(120);
            jTable1.getColumnModel().getColumn(8).setMinWidth(120);
            jTable1.getColumnModel().getColumn(9).setMinWidth(100);
            jTable1.getColumnModel().getColumn(10).setMinWidth(100);
            jTable1.getColumnModel().getColumn(11).setMinWidth(80);
            jTable1.getColumnModel().getColumn(12).setMinWidth(30);
            jTable1.getColumnModel().getColumn(13).setMinWidth(30);
            jTable1.getColumnModel().getColumn(14).setMinWidth(30);
            jTable1.getColumnModel().getColumn(15).setMinWidth(30);
            jTable1.getColumnModel().getColumn(16).setMinWidth(30);
            jTable1.getColumnModel().getColumn(17).setMinWidth(30);
            jTable1.getColumnModel().getColumn(18).setMinWidth(30);
            jTable1.getColumnModel().getColumn(19).setMinWidth(30);
            jTable1.getColumnModel().getColumn(20).setMinWidth(30);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2206, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here
        // select id for clicked row

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int id = Integer.parseInt(dtm.getValueAt(jTable1.getSelectedRow(), 0).toString());
        this.idSelectedPerusahaan = id;
    }

    public int getIdRegistrasi() {
        return idRegistrasi;
    }

    public void setIdRegistrasi(int idRegistrasi) {
        this.idRegistrasi = idRegistrasi;
    }

    public int getIdSelectedPerusahaan() {
        return idSelectedPerusahaan;
    }

    public void setIdSelectedPerusahaan(int idSelectedPerusahaan) {
        this.idSelectedPerusahaan = idSelectedPerusahaan;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
