/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuesionerfix;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

import kuesionerfix.entity.Perusahaan;
import kuesionerfix.repository.PerusahaanRepository;

/**
 *
 * @author ASUS
 */
public class EditPerusahaan extends javax.swing.JFrame {

    private int idPerusahaan;
    private Map<String, String> provinsi = new HashMap<String, String>();
    private Map<String, String> kabupaten = new HashMap<String, String>();

    /**
     * Creates new form EditPerusahaan
     */
    public EditPerusahaan(int idPerusahaan) {
        initComponents();
        this.idPerusahaan = idPerusahaan;
        loadComboboxProv();
        loadPerusahaanEdit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupVisited = new javax.swing.ButtonGroup();
        buttonGroupTanamanPangan = new javax.swing.ButtonGroup();
        buttonGroupHortikultura = new javax.swing.ButtonGroup();
        buttonGroupPeternakan = new javax.swing.ButtonGroup();
        buttonGroupKehutanan = new javax.swing.ButtonGroup();
        buttonGroupPerikanan = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        provinsiCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        kabupatenCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        kecamatanCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        kjuTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        urutTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namaUsahaTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamatTA = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        faxTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bbhCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        visitedRadio = new javax.swing.JRadioButton();
        notVisitedRadio = new javax.swing.JRadioButton();
        statusCombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        adaPangan = new javax.swing.JRadioButton();
        tidakAdaPangan = new javax.swing.JRadioButton();
        tidakAdaHortikultura = new javax.swing.JRadioButton();
        adaHortikultura = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        perkebunanCombo = new javax.swing.JComboBox<>();
        adaPeternakan = new javax.swing.JRadioButton();
        tidakAdaPeternakan = new javax.swing.JRadioButton();
        tidakAdaKehutanan = new javax.swing.JRadioButton();
        adaKehutanan = new javax.swing.JRadioButton();
        adaPerikanan = new javax.swing.JRadioButton();
        tidakAdaPerikanan = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jenisUsahaUtamaCombo = new javax.swing.JComboBox<>();
        cancelBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Perusahaan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KIP");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Provinsi");

        provinsiCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Provinsi --" }));
        provinsiCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinsiComboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Kabupaten");

        kabupatenCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabupatenComboActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Kecamatan");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Kode KJU");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("No Urut");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Identitas Perusahaan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama Perusahaan Pertanian");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Alamat Perusahaan Pertanian");

        alamatTA.setColumns(20);
        alamatTA.setRows(5);
        jScrollPane3.setViewportView(alamatTA);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nomor Telepon");

        phoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTFActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Normor Faksimili");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Bentuk Badan Hukum");

        bbhCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Bentuk Badan Hukum --", "Perusahaan Negara (PN)", "Perusahaan Daerah (PD)", "Persero", "Perum", "Perseroan Terbatas (PT)", "Naamloze Vennootschap (NV)", "Commanditaire Venootschap (CV)", "Firma", "Koperasi/KUD", "Yayasan" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("DPP");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Sudah dikunjungi ? ");

        buttonGroupVisited.add(visitedRadio);
        visitedRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        visitedRadio.setForeground(new java.awt.Color(0, 0, 0));
        visitedRadio.setText("Sudah Dikunjungi");
        visitedRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitedRadioActionPerformed(evt);
            }
        });

        buttonGroupVisited.add(notVisitedRadio);
        notVisitedRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        notVisitedRadio.setForeground(new java.awt.Color(0, 0, 0));
        notVisitedRadio.setText("Belum Dikunjungi");

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Status --", "Aktif", "Tutup Sementara/TIdak Ada Kegiatan", "Belum Berproduksi", "Tidak Bersedia Diwawancarai", "Alih Usaha ke Non Pertanian", "Tutup", "TIdak Ditemukan", "Baru", "Ganda" }));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Status");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Subsektor");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Tanaman Pangan");

        buttonGroupTanamanPangan.add(adaPangan);
        adaPangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adaPangan.setForeground(new java.awt.Color(0, 0, 0));
        adaPangan.setText("Ada");

        buttonGroupTanamanPangan.add(tidakAdaPangan);
        tidakAdaPangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tidakAdaPangan.setForeground(new java.awt.Color(0, 0, 0));
        tidakAdaPangan.setText("Tidak Ada");

        buttonGroupHortikultura.add(tidakAdaHortikultura);
        tidakAdaHortikultura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tidakAdaHortikultura.setForeground(new java.awt.Color(0, 0, 0));
        tidakAdaHortikultura.setText("Tidak Ada");

        buttonGroupHortikultura.add(adaHortikultura);
        adaHortikultura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adaHortikultura.setForeground(new java.awt.Color(0, 0, 0));
        adaHortikultura.setText("Ada");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Hortikultura");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Perkebunan");

        perkebunanCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Perkebunan --", "Kokoa/cokelat", "Karet", "Kelapa sawit", "Kopi", "Teh tebu", "Tembakau", "Cengkeh", "Kelapa", "Lada", "Tanaman lainnya", "Tidak Ada" }));

        buttonGroupPeternakan.add(adaPeternakan);
        adaPeternakan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adaPeternakan.setForeground(new java.awt.Color(0, 0, 0));
        adaPeternakan.setText("Ada");

        buttonGroupPeternakan.add(tidakAdaPeternakan);
        tidakAdaPeternakan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tidakAdaPeternakan.setForeground(new java.awt.Color(0, 0, 0));
        tidakAdaPeternakan.setText("Tidak Ada");

        buttonGroupKehutanan.add(tidakAdaKehutanan);
        tidakAdaKehutanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tidakAdaKehutanan.setForeground(new java.awt.Color(0, 0, 0));
        tidakAdaKehutanan.setText("Tidak Ada");

        buttonGroupKehutanan.add(adaKehutanan);
        adaKehutanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adaKehutanan.setForeground(new java.awt.Color(0, 0, 0));
        adaKehutanan.setText("Ada");

        buttonGroupPerikanan.add(adaPerikanan);
        adaPerikanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adaPerikanan.setForeground(new java.awt.Color(0, 0, 0));
        adaPerikanan.setText("Ada");

        buttonGroupPerikanan.add(tidakAdaPerikanan);
        tidakAdaPerikanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tidakAdaPerikanan.setForeground(new java.awt.Color(0, 0, 0));
        tidakAdaPerikanan.setText("Tidak Ada");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Perikanan");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Kehutanan");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Peternakan");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Jenis Usaha Utama");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Jenis Usaha Utama");

        jenisUsahaUtamaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis Usaha --", "Padi/palawija", "Hortikultura", "Perkebunan Kakao/cokelat", "Perkebunan Karet", "Perkebunan Kelapa sawit", "Perkebunan Kopi", "Perkebunan Teh", "Perkebunan Tebu", "Perkebunan Tembakau", "Perkebunan Cengkeh", "Perkebunan Kelapa", "Perkebunan Lada", "Tanaman Perkebunan lainnya", "HPH/IUPHHK-HA", "HPHT/IUPHHK-HT/Perhutani/Kehutanan lainnya", "Penangkaran STL", "Budidaya Udang", "Budidaya Ikan lainnya di tambak", "Budidaya Ikan di laut", "Budidaya Ikan di air tawar", "Budidaya Pembenihan", "Penangkapan Ikan", "Ternak Sapi Perah", "Ternak Besar/kecil", "Unggas" }));

        cancelBtn.setBackground(new java.awt.Color(102, 153, 255));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(0, 204, 204));
        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adaPangan)
                                            .addComponent(adaHortikultura)
                                            .addComponent(adaPeternakan)
                                            .addComponent(adaKehutanan)
                                            .addComponent(adaPerikanan))
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tidakAdaHortikultura)
                                            .addComponent(tidakAdaPangan)
                                            .addComponent(tidakAdaPeternakan)
                                            .addComponent(tidakAdaKehutanan)
                                            .addComponent(tidakAdaPerikanan)))
                                    .addComponent(perkebunanCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jenisUsahaUtamaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(phoneTF)
                                            .addComponent(jScrollPane3)
                                            .addComponent(namaUsahaTF)
                                            .addComponent(faxTF)
                                            .addComponent(bbhCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(statusCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(visitedRadio)
                                                .addGap(65, 65, 65)
                                                .addComponent(notVisitedRadio))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(473, 473, 473)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(149, 149, 149)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kabupatenCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kecamatanCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(urutTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kjuTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(provinsiCombo, 0, 318, Short.MAX_VALUE))
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(namaUsahaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faxTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbhCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitedRadio)
                    .addComponent(notVisitedRadio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adaPangan)
                    .addComponent(tidakAdaPangan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adaHortikultura)
                    .addComponent(tidakAdaHortikultura))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perkebunanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adaPeternakan)
                    .addComponent(tidakAdaPeternakan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adaKehutanan)
                    .addComponent(tidakAdaKehutanan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adaPerikanan)
                    .addComponent(tidakAdaPerikanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenisUsahaUtamaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(provinsiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kabupatenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kecamatanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kjuTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(urutTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(1552, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        Connection connection = DBConnection.getConnection();
        Perusahaan perusahaan = new Perusahaan();
        perusahaan.setId(idPerusahaan);
        if (provinsiCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Provinsi harus diisi");
            return;
        }
        perusahaan.setKodeProvinsi(provinsiCombo.getSelectedItem().toString());
        if (kabupatenCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Kabupaten harus diisi");
            return;
        }
        perusahaan.setKodeKabupaten(kabupatenCombo.getSelectedItem().toString());
        if (kecamatanCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Kecamatan harus diisi");
            return;
        }
        perusahaan.setKodeKecamatan(kecamatanCombo.getSelectedItem().toString());
        if (kjuTF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Kode KJU harus diisi");
            return;
        }
        perusahaan.setKodeKJU(kjuTF.getText());
        int noUrut = Integer.parseInt(urutTF.getText());
        if (noUrut == 0) {
            JOptionPane.showMessageDialog(this, "No Urut tidak boleh 0");
            return;
        }
        String query = "SELECT * FROM perusahaan WHERE no_urut = ?";
        try {
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            preparedStatement.setInt(1, noUrut);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                JOptionPane.showMessageDialog(this, "No Urut sudah ada");
                return;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        perusahaan.setKodeUrut(noUrut);
        if (namaUsahaTF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nama usaha harus diisi");
            return;
        }
        perusahaan.setNamaPerusahaan(namaUsahaTF.getText());
        if (alamatTA.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Alamat harus diisi");
            return;
        }
        perusahaan.setAlamatPerusahaan(alamatTA.getText());
        if (phoneTF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Telepon harus diisi");
            return;
        }
        perusahaan.setNoTelp(phoneTF.getText());
        if (faxTF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Faksimili harus diisi");
            return;
        }
        perusahaan.setNoFax(faxTF.getText());
        if (bbhCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Bentuk Badan Hukum harus diisi");
            return;
        }
        perusahaan.setBentukBadanHukum(bbhCombo.getSelectedItem().toString());
        if (buttonGroupVisited.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Kunjungan harus diisi");
            return;
        }
        String visited = "";
        if (visitedRadio.isSelected()) {
            visited = "Sudah dikunjungi mendapatkan informasi dari pihak lain(dinas dll)";
        } else {
            visited = "Belum dikonfirmasi keberadaannya";
        }
        perusahaan.setVisited(visited);
        if (statusCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Status harus diisi");
            return;
        }
        perusahaan.setStatus(statusCombo.getSelectedItem().toString());
        if (buttonGroupTanamanPangan.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Tanaman Pangan harus diisi");
            return;
        }
        String tanamanPangan = "";
        if (adaPangan.isSelected()) {
            tanamanPangan = "Ada";
        } else {
            tanamanPangan = "Tidak Ada";
        }
        perusahaan.setTanamanPangan(tanamanPangan);
        if (buttonGroupHortikultura.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Hortikultura harus diisi");
            return;
        }
        String hortikultura = "";
        if (adaHortikultura.isSelected()) {
            hortikultura = "Ada";
        } else {
            hortikultura = "Tidak Ada";
        }
        perusahaan.setHortikultura(hortikultura);
        if (perkebunanCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Perkebunan harus diisi");
            return;
        }
        perusahaan.setPerkebunan(perkebunanCombo.getSelectedItem().toString());
        if (buttonGroupPeternakan.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Peternakan harus diisi");
            return;
        }
        String peternakan = "";
        if (adaPeternakan.isSelected()) {
            peternakan = "Ada";
        } else {
            peternakan = "Tidak Ada";
        }
        perusahaan.setPeternakan(peternakan);
        if (buttonGroupPerikanan.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Perikanan harus diisi");
            return;
        }
        String perikanan = "";
        if (adaPerikanan.isSelected()) {
            perikanan = "Ada";
        } else {
            perikanan = "Tidak Ada";
        }
        perusahaan.setPerikanan(perikanan);
        if (buttonGroupKehutanan.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Kehutanan harus diisi");
            return;
        }
        String kehutanan = "";
        if (adaKehutanan.isSelected()) {
            kehutanan = "Ada";
        } else {
            kehutanan = "Tidak Ada";
        }
        perusahaan.setKehutanan(kehutanan);
        if (jenisUsahaUtamaCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Jenis usaha utama harus diisi");
            return;
        }
        perusahaan.setJenisUsahaUtama(jenisUsahaUtamaCombo.getSelectedItem().toString());
        PerusahaanRepository perusahaanRepository = new PerusahaanRepository(connection);
        perusahaanRepository.update(perusahaan);
        this.dispose();
    }//GEN-LAST:event_editBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_editBtnMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_editBtnMouseClicked

    private void provinsiComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_provinsiComboActionPerformed
        // TODO add your handling code here:
        loadComboboxKabupaten();
    }// GEN-LAST:event_provinsiComboActionPerformed

    private void kabupatenComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_kabupatenComboActionPerformed
        // TODO add your handling code here:
        loadComboboxKecamatan();
    }// GEN-LAST:event_kabupatenComboActionPerformed

    private void phoneTFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phoneTFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_phoneTFActionPerformed

    private void visitedRadioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_visitedRadioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_visitedRadioActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_cancelBtnActionPerformed

    public void loadComboboxProv() {
        String sql = "SELECT * FROM provinsi";
        Connection connection = DBConnection.getConnection();
        try {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                provinsiCombo.addItem(rs.getString("nama"));
                provinsi.put(rs.getString("nama"), rs.getString("id"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    }

    public void loadComboboxKabupaten() {
        String kodeProv = provinsi.get(provinsiCombo.getSelectedItem());
        kabupatenCombo.removeAllItems();
        String sql = "SELECT * FROM kabupaten WHERE id_prov = " + kodeProv;
        Connection connection = DBConnection.getConnection();
        kabupatenCombo.addItem("-- Pilih Kabupaten --");
        try {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                kabupatenCombo.addItem(rs.getString("nama"));
                kabupaten.put(rs.getString("nama"), rs.getString("id_kab"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    }

    public void loadComboboxKecamatan() {
        String kodeKab = kabupaten.get(kabupatenCombo.getSelectedItem());
        kecamatanCombo.removeAllItems();
        String sql = "SELECT * FROM kecamatan WHERE id_kab = " + kodeKab;
        Connection connection = DBConnection.getConnection();
        kecamatanCombo.addItem("-- Pilih Kecamatan --");
        try {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                kecamatanCombo.addItem(rs.getString("nama"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    }

    public void loadPerusahaanEdit() {
        String sql = "SELECT * FROM perusahaan WHERE id = '" + idPerusahaan + "'";
        try {
            Connection connection = DBConnection.getConnection();
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            if (rs.next()) {
                provinsiCombo.setSelectedItem(rs.getString("kode_prov"));
                kabupatenCombo.setSelectedItem(rs.getString("kode_kab"));
                kecamatanCombo.setSelectedItem(rs.getString("kode_kec"));
                kjuTF.setText(rs.getString("kode_kju"));
                urutTF.setText(rs.getString("no_urut"));
                namaUsahaTF.setText(rs.getString("nama_perusahaan"));
                alamatTA.setText(rs.getString("alamat_perusahaan"));
                phoneTF.setText(rs.getString("no_phone"));
                faxTF.setText(rs.getString("no_faksimili"));
                bbhCombo.setSelectedItem(rs.getString("bentuk_badan_hukum"));
                boolean visited = rs.getString("visited")
                        .equals("Sudah dikunjungi mendapatkan informasi dari pihak lain(dinas dll)");
                if (visited) {
                    visitedRadio.setSelected(true);
                } else {
                    notVisitedRadio.setSelected(true);
                }
                statusCombo.setSelectedItem(rs.getString("status"));
                boolean tanamanPangan = rs.getString("tanaman_pangan").equals("Ada") ? true : false;
                if (tanamanPangan) {
                    adaPangan.setSelected(true);
                } else {
                    tidakAdaPangan.setSelected(true);
                }
                boolean hortikultura = rs.getString("hortikultura").equals("Ada") ? true : false;
                if (hortikultura) {
                    adaHortikultura.setSelected(true);
                } else {
                    tidakAdaHortikultura.setSelected(true);
                }
                perkebunanCombo.setSelectedItem(rs.getString("perkebunan"));
                boolean perikanan = rs.getString("perikanan").equals("Ada") ? true : false;
                if (perikanan) {
                    adaPerikanan.setSelected(true);
                } else {
                    tidakAdaPerikanan.setSelected(true);
                }
                boolean peternakan = rs.getString("peternakan").equals("Ada") ? true : false;
                if (peternakan) {
                    adaPeternakan.setSelected(true);
                } else {
                    tidakAdaPeternakan.setSelected(true);
                }
                boolean kehutanan = rs.getString("kehutanan").equals("Ada") ? true : false;
                if (kehutanan) {
                    adaKehutanan.setSelected(true);
                } else {
                    tidakAdaKehutanan.setSelected(true);
                }
                jenisUsahaUtamaCombo.setSelectedItem(rs.getString("jenis_usaha_utama"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPerusahaan(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adaHortikultura;
    private javax.swing.JRadioButton adaKehutanan;
    private javax.swing.JRadioButton adaPangan;
    private javax.swing.JRadioButton adaPerikanan;
    private javax.swing.JRadioButton adaPeternakan;
    private javax.swing.JTextArea alamatTA;
    private javax.swing.JComboBox<String> bbhCombo;
    private javax.swing.ButtonGroup buttonGroupHortikultura;
    private javax.swing.ButtonGroup buttonGroupKehutanan;
    private javax.swing.ButtonGroup buttonGroupPerikanan;
    private javax.swing.ButtonGroup buttonGroupPeternakan;
    private javax.swing.ButtonGroup buttonGroupTanamanPangan;
    private javax.swing.ButtonGroup buttonGroupVisited;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField faxTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jenisUsahaUtamaCombo;
    private javax.swing.JComboBox<String> kabupatenCombo;
    private javax.swing.JComboBox<String> kecamatanCombo;
    private javax.swing.JTextField kjuTF;
    private javax.swing.JTextField namaUsahaTF;
    private javax.swing.JRadioButton notVisitedRadio;
    private javax.swing.JComboBox<String> perkebunanCombo;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JComboBox<String> provinsiCombo;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JRadioButton tidakAdaHortikultura;
    private javax.swing.JRadioButton tidakAdaKehutanan;
    private javax.swing.JRadioButton tidakAdaPangan;
    private javax.swing.JRadioButton tidakAdaPerikanan;
    private javax.swing.JRadioButton tidakAdaPeternakan;
    private javax.swing.JTextField urutTF;
    private javax.swing.JRadioButton visitedRadio;
    // End of variables declaration//GEN-END:variables
}
